In [3]:
import pyodbc
import pandas
import json

with open('login_creds.json') as f:
    login = json.load(f)

conn_str = (
    r'Driver=SQL Server;'
    r'Server=ccgbootcamp.database.windows.net;'
    r'Database=EDW;' + 
    'UID={};'.format(login['username']) +
    'PWD={};'.format(login['password'])
    )
cnxn = pyodbc.connect(conn_str)

In [4]:
def query_db(query, connection):

    cursor = connection.cursor()
    cursor.execute(query)
    rows = []
    for row in cursor.fetchall():
        rows.append(row)
    columns = [column[0] for column in cursor.description]

    df = pandas.DataFrame.from_records(rows, columns = columns)
    
    return df

In [5]:
sale = query_db("SELECT f.*, d.FullDate FROM FactSales f JOIN DimDate d on d.datekey = f.datekey", cnxn)
customer = query_db("SELECT * FROM DimCustomer", cnxn)

In [6]:
# Let's call our high spenders customers who have purchased over $275,000 worth of products.
# Low spenders are below.
total_sales_by_customer = sale.groupby('CustomerKey').TotalSaleAmt.sum().astype(float)

total_sales_by_customer.describe()

count       663.000000
mean     267925.002112
std       57161.915495
min        7240.200000
25%      242718.475000
50%      277334.000000
75%      304468.375000
max      384393.350000
Name: TotalSaleAmt, dtype: float64

In [7]:
# Here, we'll calculate the column we will train a model to predict. This is a simple transformation of 
# the customer's total spend. If it's over $275,000, this value will be High Spender, and if below, Low Spender.

total_sales_by_customer = total_sales_by_customer.reset_index()
total_sales_by_customer['LifetimeValue'] = 'Low Spender'
total_sales_by_customer.loc[total_sales_by_customer.TotalSaleAmt > 275000, 'LifetimeValue'] = 'High Spender'

In [ ]:
# We'll try to predict which customers will be high spenders and which will be low spenders over the course of their 
# engagement with the business. 

# What type of problem is this? Classification, regression, or unsupervised?

In [ ]:








# Classification! 

# We could also solve this as a regression problem if we wanted to predict the actual dollar amount the customer would 
# bring us. But since we are just trying to "classify" our customers into high and low life-time spend, this is a classification
# problem.

In [ ]:
# So. Let's create a training dataset so that we can train a model to learn patterns in our customers that might indicate
# if they end up becoming high spenders or low spenders. 

# Once our model is trained, we can then use it to make predictions for future customers, where we don't know the "right"
# answer yet- what their fate is with our company!

# For our data, everything is historically captured. We know the "right" answer- if the customers end up as high spenders or
# low spenders. So, we have to simulate some training data such that we don't yet "know the right answer".

# You'll see what I mean.

In [30]:
from datetime import datetime

# Data type conversion
sale['FullDate'] = sale['FullDate'].astype(str).apply(lambda x: datetime.fromisoformat(x))
sale['UnitSalePrice'] = sale['UnitSalePrice'].astype(float)

sale_dataset = sale.copy()
sale_dataset = sale_dataset.groupby('CustomerKey').FullDate.min().rename('FirstSaleDate').reset_index()

sale_dataset['OneYearAfter'] = sale_dataset['FirstSaleDate'].apply(lambda x: x.replace(year = x.year + 1))

In [31]:
# To create training data, let's act like we only have a year of data on our customers. We'll generate features only off
# of this one year of data. In real life, when we want to use our model moving forward, we'll be able to use it to 
# predict high/low lifetime spend for customers that have been with us for one year. This is all the information we'll have,
# so we're pretending it's all we have here!
sale_features = sale.copy()
sale_features = sale_features.merge(sale_dataset, on = 'CustomerKey')
sale_features = sale_features[sale_features.FullDate < sale_features.OneYearAfter]

In [20]:
# From this data, we have information on customer purchases during their first year of engagement with the company. 
# We also have some information related to the customer from DimCustomer. 

# What are some things we can think of that might be predictive of a customer becoming a high spender/low spender?
# If you had to make a guess for each customer, what are some thing that you might want to know about them to help you
# determine this? 

# These pieces of information are called our "features". We'll eventually feed them to our model so that it can learn patterns
# in the pieces of information and how they are associated with a liklihood of becoming a high spender or a low spender.

# Some pieces of information that I would think of if I was trying to decide (that we also have available in our data):
# - How many purchases have they made so far?
# - How much money have they spent with us so far?
# - Have they bought a lot of different products with us, or just a few?
# - Do they tend to buy expensive products? 
# - Do they tend to buy a lot of units of product?

# - Do they have a credit limit?
# - What type of customer are they? (Novelty Shop, Gift Store, etc.)

# sale_features
# customer

In [33]:
# We have the data for all of these features, but they aren't in the exact right format to pass to a model. 

# For example, in the data we can find our how many purchases a person has made, but currently, our table has a different
# row for each purchase. We're really looking for all of our features at the customer grain - each row is one customer, 
# with one value for each feature above. Customer Key: 1, PurchasesMade: 50, TotalSpend: $50,000, etc.

# Let's do some ~feature engineering~ to create these features and add them to our dataset!

purchases_made = sale_features.groupby('CustomerKey').DateKey.nunique().rename('PurchasesMade').reset_index()
total_spend = sale_features.groupby('CustomerKey').TotalSaleAmt.sum().rename('TotalSpend').reset_index()
unique_products = sale_features.groupby('CustomerKey').ProductKey.nunique().rename('UniqueProductCount').reset_index()
avg_unit_price = sale_features.groupby('CustomerKey').UnitSalePrice.mean().rename('AvgUnitPrice').reset_index()
avg_units = sale_features.groupby('CustomerKey').UnitQuantitySold.mean().rename('AvgUnitsBought').reset_index()

customer_features = customer[['CustomerKey', 'CreditLimit', 'CustomerType']]

customer_features = customer_features.merge(purchases_made).merge(total_spend).merge(unique_products).merge(avg_unit_price).merge(avg_units)

In [34]:
# Cool, so we have created some additional piece of information associated with our customers that may help a model 
# identify patterns and make accurate predictions.

customer_features

,CustomerKey,CreditLimit,CustomerType,PurchasesMade,TotalSpend,UniqueProductCount,AvgUnitPrice,AvgUnitsBought
0,1,None,Novelty Shop,36,92707.6000,97,44.238651,40.666667
1,2,None,Novelty Shop,27,50135.0000,78,29.394891,41.695652
2,3,None,Novelty Shop,36,101489.6500,102,34.383088,29.875000
3,4,None,Novelty Shop,33,94550.6500,94,49.356552,39.293103
4,5,None,Novelty Shop,27,67880.4000,81,50.424286,37.224490
...,...,...,...,...,...,...,...,...
658,659,1600.00,Computer Store,17,47216.2500,52,34.240357,48.178571
659,660,1900.00,Gift Store,13,54552.4000,46,77.557000,41.600000
660,661,1800.00,Supermarket,8,13208.1000,28,45.761667,34.266667
661,662,1100.00,Corporate,4,7240.2000,14,36.086667,36.866667
662,663,1600.00,Computer Store,3,22829.6500,29,40.867931,54.344828

In [ ]:
# But we aren't done yet! We still need to do some additional processing on these features for our model to get the most 
# out of them. 

# For numeric or "continuous" features, like spend and price above, many algorithms prefer these values to be "normalized" 
# by subtracting their mean and dividing by their standard deviation. This puts all of the numeric values in the same scale.
# We're going to be testing out a random forest classifier for our algorithm, which is okay with unnormalized values, so 
# for our purposes we'll leave them as is. 

# For features that are "categorical", like the string columns above, our model won't understand how to interpret these 
# text values. Model, like computers, are smart, but very stupid, and can't read. They only understand numbers.

# Let's take our credit limit column, for example. I would like to be able to tell our model that yes, this customer has
# a credit limit, or no, this customer does not. 
# Up above though, we have

In [29]:
# What are some ways you can think of that we could improve our model's performance? 
# Think - what additional data could we get? What other features could we make?